# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.workspace }}/demosite/requirements.txt
    - name: Run migrations
      run: python ${{ github.workspace }}/demosite/demosite/manage.py migrate
    - name: Build with Maven
      env:
        BROWSERSTACK_BUILD_NAME: ${GITHUB_WORKFLOW}
        BROWSERSTACK_PROJECT: ${GITHUB_RUN_ID}
        BROWSERSTACK_USERNAME: ${{secrets.BROWSERSTACK_USERNAME}}
        BROWSERSTACK_ACCESS_KEY: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
      run: |
        echo ${{ env.BROWSERSTACK_BUILD_NAME }} 
        echo ${{ env.BROWSERSTACK_PROJECT }}
        BROWSERSTACK_BUILD_NAME=${{ env.BROWSERSTACK_BUILD_NAME }} BROWSERSTACK_PROJECT=${{ env.BROWSERSTACK_PROJECT }} mvn test -P parallel
      
